import type { MarkerType } from "../types";
import type { Archetype } from "./archetypes";

export type ExtraEntry = {
  canonical_id: string;
  type: MarkerType;
  display: string;
  aka?: string;
  archetype?: Archetype;
};

export const EXTRAS: ExtraEntry[] = [
  { canonical_id: "halo_effect", type: "bias", display: "Halo Effect", archetype: "authority" },
  { canonical_id: "horn_effect", type: "bias", display: "Horn Effect", archetype: "dismissal" },
  { canonical_id: "hindsight_bias", type: "bias", display: "Hindsight Bias", archetype: "identity" },
  { canonical_id: "backfire_effect", type: "bias", display: "Backfire Effect", archetype: "identity" },
  { canonical_id: "belief_perseverance", type: "bias", display: "Belief Perseverance", archetype: "identity" },
  { canonical_id: "illusory_truth_effect", type: "bias", display: "Illusory Truth Effect", aka: "repetition feels true", archetype: "repetition" },
  { canonical_id: "continued_influence_effect", type: "bias", display: "Continued Influence Effect", aka: "debunked info still sticks", archetype: "repetition" },
  { canonical_id: "loss_aversion", type: "bias", display: "Loss Aversion Exploitation", archetype: "fear" },
  { canonical_id: "endowment_effect", type: "bias", display: "Endowment Effect", archetype: "identity" },
  { canonical_id: "survivorship_bias", type: "bias", display: "Survivorship Bias", archetype: "generalization" },
  { canonical_id: "selection_bias", type: "bias", display: "Selection Bias", archetype: "generalization" },
  { canonical_id: "base_rate_neglect", type: "bias", display: "Base Rate Neglect", archetype: "identity" },
  { canonical_id: "conjunction_fallacy_bias", type: "bias", display: "Conjunction Fallacy", aka: "Linda problem", archetype: "identity" },
  { canonical_id: "gamblers_fallacy_bias", type: "bias", display: "Gambler's Fallacy", archetype: "false_causation" },
  { canonical_id: "authority_bias", type: "bias", display: "Authority Bias", archetype: "authority" },
  { canonical_id: "mere_exposure_effect", type: "bias", display: "Mere-Exposure Effect", archetype: "repetition" },
  { canonical_id: "false_consensus_effect", type: "bias", display: "False Consensus Effect", archetype: "identity" },
  { canonical_id: "just_world_hypothesis", type: "bias", display: "Just-World Hypothesis", archetype: "identity" },
  { canonical_id: "self_serving_bias", type: "bias", display: "Self-Serving Bias", archetype: "identity" },
  { canonical_id: "fundamental_attribution_error", type: "bias", display: "Fundamental Attribution Error", archetype: "identity" },
  { canonical_id: "naive_realism", type: "bias", display: "Naïve Realism", archetype: "identity" },
  { canonical_id: "bias_blind_spot", type: "bias", display: "Bias Blind Spot", archetype: "identity" },
  { canonical_id: "outcome_bias", type: "bias", display: "Outcome Bias", archetype: "identity" },
  { canonical_id: "optimism_bias", type: "bias", display: "Optimism Bias", archetype: "identity" },
  { canonical_id: "affect_heuristic", type: "bias", display: "Affect Heuristic", archetype: "emotion" },
  { canonical_id: "representativeness_heuristic", type: "bias", display: "Representativeness Heuristic", archetype: "generalization" },
  { canonical_id: "spotlight_effect", type: "bias", display: "Spotlight Effect", archetype: "identity" },
  { canonical_id: "curse_of_knowledge", type: "bias", display: "Curse of Knowledge", archetype: "identity" },
  { canonical_id: "tu_quoque", type: "fallacy", display: "Tu Quoque", aka: "whataboutism", archetype: "redirection" },
  { canonical_id: "no_true_scotsman", type: "fallacy", display: "No True Scotsman", archetype: "false_binary" },
  { canonical_id: "composition_fallacy", type: "fallacy", display: "Composition Fallacy", archetype: "generalization" },
  { canonical_id: "division_fallacy", type: "fallacy", display: "Division Fallacy", archetype: "generalization" },
  { canonical_id: "genetic_fallacy", type: "fallacy", display: "Genetic Fallacy", archetype: "dismissal" },
  { canonical_id: "loaded_question", type: "fallacy", display: "Loaded Question", aka: "complex question", archetype: "framing" },
  { canonical_id: "begging_the_question", type: "fallacy", display: "Begging the Question", archetype: "vagueness" },
  { canonical_id: "appeal_to_popularity", type: "fallacy", display: "Appeal to Popularity", aka: "bandwagon fallacy", archetype: "appeal_to" },
  { canonical_id: "appeal_to_consequences", type: "fallacy", display: "Appeal to Consequences", archetype: "appeal_to" },
  { canonical_id: "texas_sharpshooter", type: "fallacy", display: "Texas Sharpshooter", archetype: "identity" },
  { canonical_id: "gish_gallop", type: "fallacy", display: "Gish Gallop", archetype: "redirection" },
  { canonical_id: "galileo_gambit", type: "fallacy", display: "Galileo Gambit", archetype: "identity" },
  { canonical_id: "argument_from_incredulity", type: "fallacy", display: "Argument from Incredulity", archetype: "identity" },
  { canonical_id: "argument_from_silence", type: "fallacy", display: "Argument from Silence", archetype: "burden" },
  { canonical_id: "middle_ground_fallacy", type: "fallacy", display: "Middle Ground Fallacy", aka: "argument to moderation", archetype: "false_binary" },
  { canonical_id: "special_pleading", type: "fallacy", display: "Special Pleading", archetype: "burden" },
  { canonical_id: "fallacy_fallacy", type: "fallacy", display: "Fallacy Fallacy", archetype: "dismissal" },
  { canonical_id: "continuum_fallacy", type: "fallacy", display: "Continuum Fallacy", aka: "fallacy of the beard", archetype: "vagueness" },
  { canonical_id: "single_cause_fallacy", type: "fallacy", display: "Single Cause Fallacy", archetype: "false_causation" },
  { canonical_id: "is_ought_fallacy", type: "fallacy", display: "Is-Ought Fallacy", archetype: "appeal_to" },
  { canonical_id: "reification_fallacy", type: "fallacy", display: "Reification Fallacy", archetype: "vagueness" },
  { canonical_id: "plurium_interrogationum", type: "fallacy", display: "Plurium Interrogationum", aka: "many questions", archetype: "framing" },
  { canonical_id: "ad_lapidem", type: "fallacy", display: "Argumentum ad Lapidem", aka: "dismissal without reason", archetype: "dismissal" },
  { canonical_id: "stolen_concept", type: "fallacy", display: "Stolen Concept", archetype: "vagueness" },
  { canonical_id: "etymological_fallacy", type: "fallacy", display: "Etymological Fallacy", archetype: "vagueness" },
  { canonical_id: "loaded_language", type: "rhetoric", display: "Loaded Language", archetype: "framing" },
  { canonical_id: "weasel_words", type: "rhetoric", display: "Weasel Words", aka: "\"some say\", \"many believe\"", archetype: "vagueness" },
  { canonical_id: "false_urgency", type: "rhetoric", display: "False Urgency", archetype: "fear" },
  { canonical_id: "absolutism", type: "rhetoric", display: "Absolutism", aka: "never / always / only", archetype: "generalization" },
  { canonical_id: "vagueness", type: "rhetoric", display: "Vagueness / Hand-waving", archetype: "vagueness" },
  { canonical_id: "glittering_generalities", type: "rhetoric", display: "Glittering Generalities", archetype: "vagueness" },
  { canonical_id: "dog_whistles", type: "rhetoric", display: "Dog Whistles", archetype: "in_group" },
  { canonical_id: "innuendo", type: "rhetoric", display: "Innuendo", archetype: "vagueness" },
  { canonical_id: "repetition_emphasis", type: "rhetoric", display: "Repetition for Emphasis", archetype: "repetition" },
  { canonical_id: "pejorative_framing", type: "rhetoric", display: "Pejorative Framing", archetype: "framing" },
  { canonical_id: "euphemism", type: "rhetoric", display: "Euphemism", archetype: "framing" },
  { canonical_id: "dysphemism", type: "rhetoric", display: "Dysphemism", archetype: "framing" },
  { canonical_id: "imprecise_quantifiers", type: "rhetoric", display: "Imprecise Quantifiers", archetype: "vagueness" },
  { canonical_id: "hedge_words", type: "rhetoric", display: "Hedge Words", aka: "\"might\", \"could be\"", archetype: "vagueness" },
  { canonical_id: "code_words", type: "rhetoric", display: "Code Words", archetype: "in_group" },
];
